"""Auto-generated migration

Revision ID: 0d81b9f81087
Revises: 57d7a2885542
Create Date: 2023-09-24 18:05:27.255127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d81b9f81087'
down_revision = '57d7a2885542'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
