"""Auto-generated migration

Revision ID: 410cf692768b
Revises: c8f5583b6469
Create Date: 2023-09-24 17:50:01.570832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '410cf692768b'
down_revision = 'c8f5583b6469'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
