"""Auto-generated migration

Revision ID: 57d7a2885542
Revises: 410cf692768b
Create Date: 2023-09-24 17:51:30.619703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57d7a2885542'
down_revision = '410cf692768b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
