"""Auto-generated migration

Revision ID: bdb7231910ea
Revises: 4aa8919a36f1
Create Date: 2023-09-29 00:51:18.919454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdb7231910ea'
down_revision = '4aa8919a36f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
