"""Auto-generated migration

Revision ID: c205f3765fb5
Revises: 0d81b9f81087
Create Date: 2023-09-28 08:15:47.478566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c205f3765fb5'
down_revision = '0d81b9f81087'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
