"""Auto-generated migration

Revision ID: c8f5583b6469
Revises: 93a5b4492477
Create Date: 2023-09-24 17:44:04.547254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8f5583b6469'
down_revision = '93a5b4492477'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
